---
project_name: karma
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
builds:
  - main: ./cmd/karma/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}
